services:
  db:
    image: pgvector/pgvector:pg17
    container_name: memfuse_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-memfuse}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-memfuse}
      POSTGRES_DB: ${POSTGRES_DB:-memfuse}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
    driver: local
